/**
 * Deploy artifacts generated into edge builds:
 *
 *  - <outDir>/site/_headers    — immutable cache rules for the hashed
 *    asset prefixes. Honored by Cloudflare (Workers static assets,
 *    Pages) and Netlify — same format; other platforms ignore the file.
 *    Deliberately NOT `/_static/*`: copied public/ files land at the
 *    _static root un-hashed and must stay revalidatable.
 *
 *  - <outDir>/server/DEPLOY.md — per-platform recipes with this build's
 *    real paths baked in. The artifact is platform-neutral (a Hono app
 *    whose fetch is web-standard), so the recipes differ only in who
 *    provides the listener and who serves site/.
 */

export function generateHeadersFile(): string {
    return [
        '# Generated by rs-hono build. Honored by Cloudflare and Netlify;',
        '# other platforms ignore this file.',
        '/_static/chunks/*',
        '  Cache-Control: public, max-age=31536000, immutable',
        '/_static/assets/*',
        '  Cache-Control: public, max-age=31536000, immutable',
        '',
    ].join('\n');
}

interface DeployDocOptions {
    outDir: string;
    /** Baked as the wrangler compatibility_date (the build date). */
    buildDate: string;
}

export function generateDeployDoc(options: DeployDocOptions): string {
    const { outDir, buildDate } = options;
    return `# Deploying this build

\`rs-hono build --target edge\` produced two artifacts — the deploy needs only these; everything else in \`${outDir}/\` is intermediate build state:

- \`${outDir}/server/app.mjs\` — the whole app as one self-contained module. It default-exports a Hono app; \`app.fetch\` is a web-standard \`(Request) => Response\` handler. \`app.mjs.map\` sits beside it for readable stack traces on platforms that accept source maps.
- \`${outDir}/site/\` — what the platform CDN serves: the client bundle and public/ under \`_static/\`, prerendered pages at their real paths, and a \`_headers\` file with immutable cache rules (honored by Cloudflare and Netlify).

Verify locally first: \`rs-hono preview\` serves site/ + app.mjs exactly the way a platform would.

## Cloudflare Workers

\`\`\`jsonc
// wrangler.jsonc
{
    "name": "my-app",
    "main": "${outDir}/server/app.mjs",
    "compatibility_date": "${buildDate}",
    "assets": { "directory": "${outDir}/site" },
    "upload_source_maps": true
}
\`\`\`

Then \`wrangler dev\` to test, \`wrangler deploy\` to ship.

## Bun

\`bun run ${outDir}/server/app.mjs\` serves the default export on $PORT. Nothing serves site/ — front it with a CDN, or compose a static handler the way \`rs-hono preview\` does.

## Deno

\`\`\`ts
import app from './${outDir}/server/app.mjs';
Deno.serve(app.fetch);
\`\`\`

Same statics note as Bun.

## Vercel · Netlify · AWS Lambda (adapter platforms)

Hono ships the event translators — the wrapper is three lines:

\`\`\`ts
import { handle } from 'hono/vercel'; // or 'hono/netlify', 'hono/aws-lambda', 'hono/lambda-edge'
import app from './${outDir}/server/app.mjs';
export default handle(app); // aws-lambda: export const handler = handle(app)
\`\`\`

Map \`${outDir}/site\` to the platform's static hosting (Vercel build output, Netlify publish directory, S3 behind CloudFront).

**CloudFront note:** it does not rewrite \`/signup\` → \`/signup/index.html\` for subdirectories. Either add a CloudFront Function for index rewrites, or let those requests fall through to the Lambda — they render server-side, which is the designed fallback.

## Runtime caveats

- Most edge runtimes have no \`process.env\` — read request-scoped env with \`env(c)\` from \`hono/adapter\`. \`PUBLIC_\`-prefixed values are baked in at build time (matching the client bundle).
- \`config.server.onStart\` runs at module evaluation — keep it light on Workers (cold-start CPU budget).
- Anything importing \`node:*\` in loaders/endpoints fails on non-Node runtimes.
`;
}
