// Everything the scaffolder knows about the framework, generated from the framework itself.
//
// Two things have to agree with `packages/rshono` and would rot silently if they were typed out here:
// the dependency versions a generated app pins (React in particular — rshono's RSC internals are
// coupled across builds, and an app installed with npm or bun has no `pnpm-workspace.yaml` overrides
// to keep a single copy), and the list of deploy targets with the command each one is deployed by.
// Add a target to `deploy/presets.ts` and the CLI offers it after a rebuild, with no edit here.
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const packageDir = join(import.meta.dirname, '..');

const frameworkManifest = require.resolve('@rshono/core/package.json');
const framework = JSON.parse(readFileSync(frameworkManifest, 'utf8'));
const frameworkDir = dirname(frameworkManifest);

const presetsPath = join(frameworkDir, 'dist', 'deploy', 'presets.js');
let presets;
try {
  presets = await import(pathToFileURL(presetsPath).href);
} catch (cause) {
  throw new Error(`[create-rshono] cannot read ${presetsPath} — build the framework first (\`pnpm --filter @rshono/core build\`).`, { cause });
}

/**
 * The versions the framework is *tested* against, not the ranges it merely accepts. `react` and
 * `react-dom` are exact in rshono's own devDependencies for the reason above, and copying the
 * declaration verbatim carries that exactness into every scaffolded app.
 */
const TEMPLATE_DEPS = ['hono', 'react', 'react-dom', 'typescript', '@types/node', '@types/react'];

const tested = {};
for (const name of TEMPLATE_DEPS) {
  const range = framework.devDependencies[name];
  if (!range) throw new Error(`[create-rshono] rshono no longer declares a tested version of "${name}" — update TEMPLATE_DEPS.`);
  tested[name] = range;
}

const targets = presets.DEPLOY_TARGETS.map((name) => {
  const hint = presets.deployHintFor(name);
  if (!hint) throw new Error(`[create-rshono] deploy target "${name}" has no deployHint.`);
  return { name, hint };
});

const entries = (record) =>
  Object.entries(record)
    .map(([key, value]) => `  ${/^[a-z][a-z\d]*$/i.test(key) ? key : `'${key}'`}: '${value}',`)
    .join('\n');

const file = `// GENERATED by scripts/codegen.mjs from packages/rshono — do not edit. Run \`pnpm --filter @rshono/create codegen\`.

/** The framework release a scaffolded app is pinned to: this package and rshono ship together. */
export const RSHONO_VERSION = '${framework.version}';

/**
 * The dependency versions rshono is tested against, copied from its own manifest. Exact where it is
 * exact — React's RSC internals are coupled across builds, and a generated app has no workspace
 * overrides to fall back on.
 */
export const FRAMEWORK_DEPS = {
${entries(tested)}
} as const;

/** Every \`deploy\` target the installed framework knows, with the command that ships what it built. */
export const DEPLOY_TARGETS = [
${targets.map((target) => `  { name: '${target.name}', hint: '${target.hint.replaceAll("'", "\\'")}' },`).join('\n')}
] as const;

export type DeployTargetName = (typeof DEPLOY_TARGETS)[number]['name'];
`;

const outDir = join(packageDir, 'src', 'generated');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'framework.ts'), file);

console.log(`  • generated src/generated/framework.ts — rshono ${framework.version}, ${targets.length} deploy target(s)`);
