/**
 * Node composition & app handler.
 *
 * buildNodeApp assembles the portable Hono app (app.tsx) with its Node
 * runtime pieces: pipeable-stream SSR, filesystem statics, and the
 * prerendered-page lookup. It is used two ways:
 *   - createAppHandler (dev/start/build): loads routes.ts / the sub-app
 *     from disk first, then composes
 *   - the entry generated by `rs-hono build --target node`, which
 *     imports routes/config statically and calls buildNodeApp directly
 */
import type { Hono, MiddlewareHandler } from 'hono';
import { existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import type { RsHonoConfig } from '../config.js';
import { isPageRoute, type Route } from '../router.js';
import { buildApp } from './app.js';
import { loadRoutes, loadServerApp } from './load.js';
import { readPrerendered } from './ssg.js';
import { renderToStream } from './ssr.js';
import { createStaticMiddleware } from './static.js';

export interface NodeAppOptions {
    routes: Route[];
    subApp?: Hono;
    middleware?: MiddlewareHandler;
    /** Root directory of the user's project (or deploy root for bundles). */
    rootDir: string;
    /** Output directory name (client bundle lives in <outDir>/client). */
    outDir: string;
    /** Public/static directory name. */
    publicDir: string;
    isDev: boolean;
}

/** Compose the portable app with the Node runtime (fs statics, SSG, pipeable SSR). */
export function buildNodeApp(options: NodeAppOptions): Hono {
    const { routes, subApp, middleware, rootDir, outDir, publicDir, isDev } = options;

    // The client bundle is written to <outDir>/client (chunks/, assets/).
    // In dev, the public dir is served as-is alongside it; in prod, the
    // build copies public/ into <outDir>/client so one root suffices.
    const clientOut = join(rootDir, outDir, 'client');
    if (isDev) {
        // The Rspack watcher may not have produced the first bundle yet.
        mkdirSync(clientOut, { recursive: true });
    }
    const staticRoots = (isDev ? [join(rootDir, publicDir), clientOut] : [clientOut])
        // A project without a public/ dir is fine — don't serve (or warn
        // about) roots that don't exist.
        .filter((root) => existsSync(root));

    // In prod, static routes prerendered by `rs-hono build` are served
    // from <outDir>/ssg; anything else falls back to per-request SSR.
    const ssgDir = isDev ? undefined : join(rootDir, outDir, 'ssg');

    return buildApp({
        routes,
        subApp,
        isDev,
        middleware,
        render: renderToStream,
        staticApp: createStaticMiddleware({ roots: staticRoots, isDev }),
        readPrerendered: ssgDir ? (requestPath) => readPrerendered(ssgDir, requestPath) : undefined,
    });
}

interface HandlerOptions {
    config: RsHonoConfig;
    rootDir: string;
    isDev: boolean;
}

export async function createAppHandler(options: HandlerOptions) {
    const { config, rootDir, isDev } = options;

    let routes;
    try {
        routes = await loadRoutes(rootDir);
    } catch (err) {
        console.error('  ✗ Failed to load src/routes.ts:');
        console.error(err);
        throw err;
    }
    if (routes === null) {
        console.log('  • No src/routes.ts found — no pages will be served.');
    }

    const subApp = await loadServerApp(rootDir);

    const all = routes ?? [];
    console.log('  • Routes mounted:');
    console.log(`    - ${all.filter(isPageRoute).length} pages`);
    console.log(`    - ${all.filter((r) => r.kind === 'endpoint').length} endpoints`);
    if (subApp) console.log('    - 1 server sub-app');

    const app = buildNodeApp({
        routes: routes ?? [],
        subApp,
        middleware: config.server?.middleware,
        rootDir,
        outDir: config.outDir ?? 'dist',
        publicDir: config.publicDir ?? 'public',
        isDev,
    });

    // Startup hook from rs-hono.config.ts
    if (config.server?.onStart) {
        await config.server.onStart();
    }

    return app.fetch;
}
